; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30038.1 

; Generated by VC++ for Common Language Runtime
.file "D:\Work\Biblio_Convert_Program\Biblio_Convert_Program\Release\.NETFramework,Version=v4.0.AssemblyAttributes.obj"
.global	
.global	
	.bss
.local	,4
.local	,4
; Function compile flags: /Ogtp
	.text
	.comdat	any, ??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z
.global	??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z ; ??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z
??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z: ; ??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z
;	.proc.def	D:V(P)

; Function Header:
; max stack depth = 1
; function size = 7 bytes
; local varsig tk = 0x0 
; Exception Information:
; 0 handlers, each consisting of filtered handlers

;	.formal.mptr 0,"_this$" SIG: Optional C Binding Modifier(token:0x826F191).class (token:0x826F193)

;	.proc.beg
; File D:\Work\Biblio_Convert_Program\Biblio_Convert_Program\predefined C++\CLI attribute types (compiler internal)
; Line 34
	ldarg.0				; _this$
	call		??0Attribute@System@@$$FI$AAM@XZ
	ret		
 .end ??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z ; ??0CppInlineNamespaceAttribute@?A0xe04397c1@vc.cppcli.attributes@@$$FQ$AAM@P$AAVString@System@@@Z
;	.proc.end.void
